### PR TITLE
Adding Estimate support for Quotes

### PR DESCRIPTION
**Pull request by jeperkins4**
This PR provides a base level of support for Estimate Records or "Sales Quotes" based upon the SuiteTalk API.

### CODE REVIEW

**Comment by iloveitaly** [comment]
Looks great! Thanks.

**Comment by pierre-pretorius** [comment]
We started using the new Estimate records thank you @jeperkins4.
@iloveitaly: Are there any plans to push to rubygems?

**Comment by iloveitaly** [comment]
Just released 0.8.6! Thanks for the reminder.

**Comment by pierre-pretorius** [comment]
@jeperkins4 I'm successfully creating estimates in NetSuite with you PR, but when I retrieve an estimate on ID I get the error below. Are you reading estimates successfully?

```
NetSuite::Records::Estimate.get(1234567)
Exception: NoMethodError: undefined method `klass=' for #<NetSuite::Records::EstimateItem:0x00005617353d5778>
--
lib/ruby/gems/2.5.0/gems/netsuite-0.8.6/lib/netsuite/support/attributes.rb:17:in `initialize_from_attributes_hash'
lib/ruby/gems/2.5.0/gems/netsuite-0.8.6/lib/netsuite/records/estimate_item.rb:21:in `initialize'
lib/ruby/gems/2.5.0/gems/netsuite-0.8.6/lib/netsuite/support/sublist.rb:65:in `new'
lib/ruby/gems/2.5.0/gems/netsuite-0.8.6/lib/netsuite/support/sublist.rb:65:in `process_sublist_item'
lib/ruby/gems/2.5.0/gems/netsuite-0.8.6/lib/netsuite/support/sublist.rb:57:in `block in process_sublist'
lib/ruby/gems/2.5.0/gems/netsuite-0.8.6/lib/netsuite/support/sublist.rb:56:in `map'
lib/ruby/gems/2.5.0/gems/netsuite-0.8.6/lib/netsuite/support/sublist.rb:56:in `process_sublist'
lib/ruby/gems/2.5.0/gems/netsuite-0.8.6/lib/netsuite/support/sublist.rb:23:in `block in sublist'
lib/ruby/gems/2.5.0/gems/netsuite-0.8.6/lib/netsuite/support/attributes.rb:15:in `block in initialize_from_attributes_hash'
lib/ruby/gems/2.5.0/gems/netsuite-0.8.6/lib/netsuite/support/attributes.rb:14:in `each'
```

When running the debugger I can see the `klass=` method isn't called when I call the same method on a customer, example:  `NetSuite::Records::Customer.get(1234)`

The following monkey patch is very ugly but solves the problem:
```
NetSuite::Records::EstimateItem.class_eval do
  def klass=(klass)
    # Ignore.
  end
end
```

**Pull request merged**
