### PR TITLE
Updated the CustomerAddressBook fields to make it work

### PR DESCRIPTION
**Pull request by cfactolerin**
Created a new record called Address and updated the CustomerAddressBook fields to make it work.

### CODE REVIEW

**Comment by iloveitaly** [comment]
@cfactolerin Thanks for the PR! What exactly was breaking with the existing implementation? It's working fine for me in a couple projects.

**Comment by cfactolerin** [comment]
Hi @iloveitaly. We encountered some errors when we were adding an Address to a Customer and when I looked at the latest schema, it's a bit different. https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2015_1/schema/other/customeraddressbook.html?mode=package

I'll try to see if I can reproduce the errors we saw and post it here. It returns an error if we create the CustomerAddressbook together with the Customer saying that CustomerAddressbook does not have fields that are in the Address object. If we create the Customer in advance and then update it with CustomerAddressbook data it will return true but somehow the Address is not added if get the customer again or in the UI.

I agree with you that this might break the existing codes you have since I removed some fields in CustomerAddressBook.

**Comment by iloveitaly** [comment]
Got it! Thanks for the explination!

Given that it will break older versions, do you think you could conditionally enable the new syntax based on the `NetSuite::Configuration.api_version` similar to this PR https://github.com/NetSweet/netsuite/pull/208

Unfortunately, without this backwards compatibility it might be a while until I can merge this in :(

**Comment by cfactolerin** [comment]
oooh so that's how you guys do it. Didn't know you can specify the version. I'll try to change it once I have the time. Sorry bout that.

**Pull request closed without merging**
