### PR TITLE
File timestamps

### PR DESCRIPTION
**Pull request by bentoncreation**
Hey, I was hoping to add :created_date and :last_modified_date to the File record.

I added File to the basic record spec, but you'll see that it's currently breaking. The weird thing is, the error message says:

```
Failure/Error: custom_object_fields = standard_fields.select { |f| !record_instance.send(f).nil? }
NoMethodError: undefined method `abbreviation' for #<NetSuite::Records::File:0x007ff3c6492520>
```

File doesn't have an :abbreviation field. I ended up inspecting what fields File reportedly had when specs are run. Here's the output:

```
#<Set: {:abbreviation, :value, :value_id, :is_inactive, :email, :give_access, :password, :password2, :send_email, :contact, :role, :phone, :first_name, :last_name, :is_support_rep, :birth_date, :hire_date, :last_review_date, :next_review_date, :title, :home_phone, :office_phone, :eligible_for_commission, :is_sales_rep, :klass, :middle_name, :account_number, :alien_number, :approval_limit, :bill_pay, :comments, :date_created, :direct_deposit, :entity_id, :expense_limit, :fax, :is_job_resource, :job_description, :labor_cost, :last_modified_date, :mobile_phone, :pay_frequency, :phonetic_name, :purchase_order_approval_limit, :purchase_order_approver, :purchase_order_limit, :release_date, :resident_status, :salutation, :social_security_number, :visa_exp_date, :visa_type, :currency, :department, :location, :subsidiary, :employee_type, :employee_status, :supervisor, :selected_role, :roles_list, :content, :description, :name, :media_type_name, :file_type, :text_file_encoding, :created_date, :folder, :url}>
```

Turns out, that's all the fields and record_refs for the following record classes: File, Employee, CustomListCustomValue, ContactAccessRoles, and Roles. All those classes are subclassing NetSuite::Support::Base. But, oddly, there are two classes (Bin and Partner) that subclass NetSuite::Support::Base, but whose fields and record_refs are not in that set.

When I checked File class fields in `bundle console`, I got what I expected:

```
#<Set: {:content, :description, :name, :media_type_name, :file_type, :text_file_encoding, :created_date, :last_modified_date, :folder, :klass, :url}> 
```

If I stop File from subclassing NetSuite::Support::Base, and add in the includes and initialize method from Base, the specs run fine. But it looked like we should be trying to stick with subclassing Base where possible.

I'm a little stumped. Any idea what could be causing this, or what to do about it?

### CODE REVIEW

**Comment by iloveitaly** [comment]
I'm pretty sure this is a meta-programming bug: my hunch [is the `@fields`](https://github.com/NetSweet/netsuite/blob/master/lib/netsuite/support/fields.rb#L14) is referring to the `Netsuite::Support::Fields` module variable instead of the class variable of the class the module was included into. Here's how I solved this issue in some `netsuite_rails` code:

https://github.com/NetSweet/netsuite_rails/blob/master/lib/netsuite_rails/record_sync.rb#L6

`class_attribute` is a rails-only method. I've seen some elegant ways of handling this issue using plain old ruby, but I can't find them right now. Want to take a shot at this and let me know if you get stuck? I don't have the time right now to dig deeper.

**Comment by bentoncreation** [comment]
Okay, now I'm wondering if it has something to do with this "bit of trickery" in the `inherited` method https://github.com/NetSweet/netsuite/blob/master/lib/netsuite/support/fields.rb#L66

Is this conflicting with the intention of subclassing from Support::Base?

**Comment by iloveitaly** [comment]
@bentoncreation I think you are right. Here's what I did:

* removed `Support::Base`
* removed the hacky field inheritance stuff. That was to save some work awhile back before I understood how nuanced some of these NetSuite records are—it's safe to remove at this point.

Could you try your changes against this PR and let me know if you have any luck https://github.com/NetSweet/netsuite/pull/253

Thanks for your help!

**Comment by bentoncreation** [comment]
Hey, thanks! It's working now. Let me know if I should do a fresh PR with just my two commits against the remove-base-class branch.

**Comment by iloveitaly** [comment]
@bentoncreation Rebasing on that branch works great. Merged with bf196d8..9c3d3a9

🚢

**Pull request closed without merging**
