### PR TITLE
Addressbook and Employee Record Updates

### PR DESCRIPTION
**Pull request by carlosplusplus**
My company, Namely, has had a fork of this gem for quite some time:
https://github.com/NetSweet/netsuite/compare/master...namely:master

We added functionality that didn't exist in current gem as of the fork, and upon further inspection, it doesn't exist in the current version. In an effort to move from our fork to the base gem, this PR:  

- Adds `Employee` functionality.
==>  `addressbook_list` added.
 ==> `default_address` and `gender` fields.

- Adds `*Addressbook*` functionality.
==> DRYs out duplicated code.
==> `EmployeeAddressbook` and `EmployeeAdressbookList` added.

- Cleans up [ 🎨 ] code / specs.

I've added descriptions to all my commit messages detailing the changes.

Looking forward to hearing back, thank you!

### CODE REVIEW

**Comment by carlosplusplus** [comment]
Hey @iloveitaly - curious to know if there's anything else you need from my end before merging in this PR. Most of this PR is shuffling around code and DRYing out repeated classes.

Let me know! Would be great to get this in and bump the gem. 😎

**Comment by iloveitaly** [comment]
@carlosplusplus Hey! Thanks for this, these are some great changes. A bit short on time right now, but I'll look at this soon and get it merged or request some minor changes.

**Comment by carlosplusplus** [comment]
Hey @iloveitaly - thanks for getting back to me!

No issues at all re: changing the attribute list back to the original style. You're absolutely right - it would feel a bit weird and out of place if only one record had this style.

I changed it back, now alphabetized with line breaks <= 80 characters, and ensured the specs now match 1-to-1 with all the attributes (a few were missing originally). Having specs in place makes refactors like this easy.

Let me know if we're good to go! 😎

**Comment by carlosplusplus** [comment]
Hey @iloveitaly - thanks for getting back to me!

No issues at all re: changing the attribute list back to the original style. You're absolutely right - it would feel a bit weird and out of place if only one record had this style.

I changed it back, now alphabetized with line breaks <= 80 characters, and ensured the specs now match 1-to-1 with all the attributes (a few were missing originally). Having specs in place makes refactors like this easy.

Let me know if we're good to go! 😎

**Comment by carlosplusplus** [comment]
Any updates here @iloveitaly ? Would love to get this merged and the gem upreved if things look good on your end. Thanks!

**Comment by iloveitaly** [comment]
@carlosplusplus running this against a large internal test suite. If it passes, I'll merge it in!

**Comment by iloveitaly** [comment]
@carlosplusplus had some failing tests on my internal test suite. I'll look into why and get back to you here.

**Comment by carlosplusplus** [comment]
Sounds good to me, @iloveitaly - thank you!

**Comment by iloveitaly** [comment]
@carlosplusplus finally getting a chance to run this against a larger test suite... I'll let you know how it goes.

**Comment by iloveitaly** [comment]
@carlosplusplus can you rebase this against the latest master branch? Should be able to get this tested and merged this week if all passes on my end.

**Comment by carlosplusplus** [comment]
Rebased off the latest `master`, @iloveitaly - thank you!

**Comment by jayhahn** [comment]
@iloveitaly Any update on this?

**Comment by iloveitaly** [comment]
@carlosplusplus @jayhahn Unfortunately open source work is last on my list :/ I'll get to this when I can!

**Pull request closed without merging**
