### PR TITLE
Record ref doesn't pick up the internal_id

### PR DESCRIPTION
**Pull request by rudyyazdi**
Hi Michael,

I was having a problem with record_ref and I figured it's happening because `RecordRef` expects the hash attribute to be something like this: `{internal_id: "44"}` but in the search result if you passed something like:

```
{
  :entity=>{:search_value=>{:@internal_id=>"11"}},
  :internal_id=>{:search_value=>{:@internal_id=>"5"}}
}

# it would turn it into:
{
  :entity=>"11",
  :internal_id=>"5"
}

# instead of this:
{
  :entity=>{:@internal_id=>"11"},
  :internal_id=>"5"}
}
```

So I added `k == :internal_id` in line 56. Hope my implementation is ok.

Cheers,

### CODE REVIEW

**Comment by rudyyazdi** [comment]
Hey @iloveitaly this last commit is completely optional, the issue was fixed by the first two commits.

The third one is some refactoring I did. Please let me know if you don't think it's a good idea or if you have any comments/suggestions.

Thanks heaps :)
Cheers.

**Comment by iloveitaly** [comment]
@rudyyazdi Thanks for this! Searching is a pretty core part of the gem, I want to make sure I dedicate the time to really dive into this PR before merging it in. I'll review this in the next 1-2 weeks or so.

**Comment by rudyyazdi** [comment]
@iloveitaly no problem, that's exactly why I wanted to make sure that it is the right move :)

If you have any sample data (e.g. `custome_records`) or you have any edge cases in mind, I'm happy to write more tests for it too.

P.S. I can also break this into two PR's one for the fix and one for the refactoring if you think that's a good idea :)

Cheers,

**Comment by iloveitaly** [comment]
> P.S. I can also break this into two PR's one for the fix and one for the refactoring if you think that's a good idea :)

@rudyyazdi if you don't mind, that would be great!

**Comment by rudyyazdi** [comment]
Hey @iloveitaly I hope all is good.

I just wanted to follow up on this PR, is there anything I can do to help?

Cheers,

**Comment by iloveitaly** [comment]
Hey @rudyyazdi, sorry for the delay here. Busy with some other projects at the moment, and the projects aren't touching this part of the code base, so I'm not able to give this a quick review. Unfortunately, this is going to have to wait 1-2 weeks because of my schedule. Apologies!

**Comment by rudyyazdi** [comment]
No worries @iloveitaly :)

Just ping me if anything needs explaining.

Cheers,

**Comment by iloveitaly** [comment]
@rudyyazdi curious if this was resolved with another recent update? Or do you still need this patch in order to resolve the issue?

**Comment by rudyyazdi** [comment]
Hey @iloveitaly hope you're well. This was for a long time ago in my previous company. It never solved for us so we were using a fork of this repo.

**Pull request closed without merging**
